/**
 * @author Maarten
 *
 * Version : $Id$
 * This file was generated by Aldebaran Robotics ModuleGenerator
 */

#include "goal_tracker.h"

#include <alvalue/alvalue.h>
#include <alcommon/alproxy.h>
#include <alcommon/albroker.h>


goal_tracker::goal_tracker(
	boost::shared_ptr<AL::ALBroker> broker,
	const std::string& name): AL::ALModule(broker, name)
{
  setModuleDescription("This is an autogenerated module, this descriptio needs to be updated.");

  functionName("echo", getName(), "A simple echo function");
  addParam("foo", "Any parameter");
  setReturn("return", "Returns the given parameter");
  BIND_METHOD(goal_tracker::echo);
}

goal_tracker::~goal_tracker() {}


AL::ALValue goal_tracker::echo(const AL::ALValue& foo)
{
  return foo;
}
