/**
 * @author Maarten
 *
 * This file was generated by Aldebaran Robotics ModuleGenerator
 */

#ifndef GOAL_TRACKER_GOAL_TRACKER_H
#define GOAL_TRACKER_GOAL_TRACKER_H

#include <boost/shared_ptr.hpp>
#include <alcommon/almodule.h>
#include <string>

namespace AL
{
  class ALBroker;
}

class goal_tracker : public AL::ALModule
{
  public:

     goal_tracker(boost::shared_ptr<AL::ALBroker> broker, const std::string& name);

    virtual ~goal_tracker();

    /**
     * echo: simply returns the paramter given as first arguemtn
     * The AL::ALValue is an union type which can be a std::string, an int, a float,
     * a vector of floats, and so on.
     */
    AL::ALValue echo(const AL::ALValue& foo);
};

#endif  // GOAL_TRACKER_GOAL_TRACKER_H

